### ISSUE TITLE
Merge preprint into master

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-moco#515]

**Comment by nickbianco** [comment]
Oh boy.

**Comment by chrisdembia** [comment]
There are two changes in `preprint` for which I would like to find alternative solutions:

1. `MocoTrajectory::setState()` accepting a `VectorView`. @nickbianco do you remember why we needed to introduce this?
2. `MocoProblemRep` handling bounds for the activation of `ActivationCoordinateActuator`s. Hopefully, the same "output for bounds" mechanism we used for DGF can work here too.
