### ISSUE TITLE
Investigate why setting periodicity constraints for controls does not work well

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-moco#528]
Brian Umberger and @nickbianco have run into this issue. It's unclear if there's a bug.

**Comment by rosshm16** [comment]
I wanted to dredge this issue back up.  I've been unable to get any simulations with a periodicity constraint on muscle controls to converge.  Periodic states and controls in gait simulations is definitely not an infeasible problem, I've generated hundreds of simulations in IPOPT with those constraints (Ton's approach uses a periodicity constraint on controls too).  So my guess is this is a bug?

**Comment by nickbianco** [comment]
@rosshm16 thanks for bringing this back up. I think I've found the issue and have created a PR for the fix that will be included in the next release. We could also send you an updated build in the meantime.

**Comment by rosshm16** [comment]
@nickbianco great!  Happy to try out an updated build when you get a chance.

**Comment by nickbianco** [comment]
@rosshm16 we just merged a fix for this issue. You can download a new version of Moco that includes the fix here: https://github.com/opensim-org/opensim-moco/actions/runs/64989737.

Let us know if this works for you. I'll leave the issue open in the meantime.

**Comment by chrisdembia** [comment]
@nickbianco I'm not sure who has access to that link. If I open an Incognito window, I cannot download the artifact.

Here's a link to the Mac build that I just saved to my Dropbox: https://www.dropbox.com/s/emel5c0k8go6lcj/opensim-moco-0.4.0-2020-03-27-52caea20-mac.zip?dl=0

**Comment by nickbianco** [comment]
@chrisdembia I tried signing out of my GitHub profile and the link appears, but I guess I didn't actually downloading it. Thanks for posting the backup link.

**Comment by rosshm16** [comment]
@nickbianco @chrisdembia I was able to download it this morning from the link Nick sent.  Will try it out tomorrow (another busy day of virtual teaching today) and report back.  It looks like this version also has the MocoContractTrackingGoal able to track GRF with multi-segment feet, I was going to try that out as well.

**Comment by chrisdembia** [comment]
Oh, good! Sorry for the link confusion, and thanks for the update.

**Comment by rosshm16** [comment]
The periodicity goal on muscle controls is working great!  I attached an example, this was from a simulation of one step of walking.  This simulation just tracked kinematic data (no GRF tracking).

I've not gotten the contact force tracking with multi-segment feet to work well yet.  It converges but the tracking is very poor.  I think it is probably user error, you can see in the example attached that it needed ~max activations from all the toe muscles.  I think it probably needs a spring-damper on the toe joint.

<img width="1149" alt="Screen Shot 2020-04-01 at 6 17 53 PM" src="https://user-images.githubusercontent.com/62774041/78192725-b61b5a00-7446-11ea-921f-686cf4542124.png">

**Comment by nickbianco** [comment]
@rosshm16 that's great! Thank you for the report. I think we can close this issue now.

The toe joint could be the culprit for your contact tracking issue. Are you using the solver's implicit multibody dynamics mode? That may help with small toe masses. But let's move that discussion to the forum or another issue if it persists.
