### ISSUE TITLE
The installed exampleMocoCustomEffortGoal does not compile on Windows

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-moco#550]
Aaron Fox is having trouble compiling exampleMocoCustomEffortGoal (the installed version) on Windows: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=1815&t=11308&p=31426&start=0&view=

**Comment by chrisdembia** [comment]
@nickbianco this is fixed now, right?

**Comment by nickbianco** [comment]
Yep, should've have referenced this issue in the PR I made.
