### ISSUE TITLE
Fix default values for createPeriodicTrajectory.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-moco#600]
In chatting with @nickbianco , we think we have the defaults for pelvis rotation and lumbar rotation are incorrect.

**Comment by chrisdembia** [comment]
@nickbianco I made a big mistake yesterday; I pushed directly to master!

Can you look over [this commit](https://github.com/opensim-org/opensim-moco/commit/11c96a19063811c535de823b6cc01726915c33d7) and let me know if you have any comments?

**Comment by nickbianco** [comment]
![image](https://user-images.githubusercontent.com/23224439/76454506-08aaae80-6392-11ea-8513-6f556190b76b.png)

**Comment by nickbianco** [comment]
That commit looks good to me.

**Comment by nickbianco** [comment]
I mean, who needs PRs anyway....

**Comment by chrisdembia** [comment]
Haha. Thanks @nickbianco
