### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by mkirby42** [opensim-org/opensim-moco#665]
#9 3214.1 [ 29%] Building CXX object OpenSim/Simulation/CMakeFiles/osimSimulation.dir/StatesTrajectory.cpp.o
------
executor failed running [/bin/sh -c cd /opensim-moco         && git submodule update --init         && mkdir ../moco_dependencies_build         && cd ../moco_dependencies_build         && cmake ../opensim-moco/dependencies         -DOPENSIM_PYTHON_WRAPPING=on         && make --jobs $(nproc) ipopt         && make --jobs $(nproc)         && echo "/moco_dependencies_install/adol-c/lib64" >> /etc/ld.so.conf.d/moco.conf         && echo "/moco_dependencies_install/ipopt/lib" >> /etc/ld.so.conf.d/moco.conf         && ldconfig         && rm -r /moco_dependencies_build]: exit code: 2
<img width="1041" alt="Screen Shot 2021-09-16 at 10 58 43 AM" src="https://user-images.githubusercontent.com/31753757/133645637-d49b58ce-e7f4-4903-8af7-6e92807af9f5.png">

**Comment by nickbianco** [comment]
Hi @mkirby42, thanks for posting the issue. I'm not sure why this fails at the moment. However, we've moved active development for the Moco project to the main OpenSim repository: https://github.com/opensim-org/opensim-core. You can try building from source there. 

Unless you need an older version of Moco from this repository for some reason?

**Comment by mkirby42** [comment]
Thanks!
