### ISSUE TITLE
OpenSim::MocoStudy::solve() will cause a crash on Google Colab

### ISSUE THREAD

**Issue by 2635215324** [opensim-org/opensim-moco#669]
When I tried to run exampleHangingMuscle(python code) on google colab, I found the 'solution = study.solve()' will cause a crash, but it will run okay on my local terminal. It's not a runtime problem, a '??solve' will case a crash on google colab as well.

**Comment by nickbianco** [comment]
Hi @2635215324, I'm not too familiar with Google colab, could you provide more information about the crash including any error messages?

Are you using OpenSim Moco 0.4.0 (the last version released from this repo), or a newer version that's included with OpenSim 4.2 or 4.3?

**Comment by 2635215324** [comment]
Hi, on Colab, the OpenSim Version Installed is version: 4.3.1.

It crashed without report errors, the server log shows that:


Timestamp | Level | Message
-- | -- | --
Jan 8, 2022, 3:24:03 PM | WARNING | WARNING:root:kernel 6cdfacdd-755b-45ed-87be-03f1a27d5421 restarted
Jan 8, 2022, 3:24:03 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Jan 8, 2022, 3:24:02 PM | WARNING | [info] Number of threads: 2
Jan 8, 2022, 3:24:02 PM | WARNING | [warning] No time bounds set.
Jan 8, 2022, 3:24:02 PM | WARNING | [warning] No time bounds set.
Jan 8, 2022, 3:24:02 PM | WARNING | Parameters: none
Jan 8, 2022, 3:24:02 PM | WARNING | Controls: none
Jan 8, 2022, 3:24:02 PM | WARNING | States: none
Jan 8, 2022, 3:24:02 PM | WARNING | Path constraints: none
Jan 8, 2022, 3:24:02 PM | WARNING | Kinematic constraints: none
Jan 8, 2022, 3:24:02 PM | WARNING | Endpoint constraints: none
Jan 8, 2022, 3:24:02 PM | WARNING | Costs: none
Jan 8, 2022, 3:24:02 PM | WARNING | [info] ------------------------------------------------------------------------
Jan 8, 2022, 3:24:02 PM | WARNING | [info] Sat Jan 8 07:24:02 2022
Jan 8, 2022, 3:24:02 PM | WARNING | [info] MocoCasADiSolver starting.
Jan 8, 2022, 3:24:02 PM | WARNING | [info] ========================================================================
Jan 8, 2022, 3:24:02 PM | WARNING | [warning] No time bounds set.
Jan 8, 2022, 3:24:02 PM | WARNING | [warning] No time bounds set.

then the server just restart.

**Comment by nickbianco** [comment]
Hi @2635215324, you might need to disable parallel processing if you're using MocoCasADiSolver, which Google Colab might not support:

```Python
solver.set_parallel(0)
```

**Comment by 2635215324** [comment]
Hi @nickbianco, thank you so much for your help.

I tried this method, but it didn't work. I still don't know the cause of this problem, but I can now run the solve() function by connecting Colab to the local runtime.

**Comment by nickbianco** [comment]
@2635215324, glad you resolved the issue!
